name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    outputs:
      artifact-name: ${{ steps.set-output.outputs.artifact-name }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Run build
      run: npm run build --if-present
      
    - name: Run tests
      run: npm test --if-present
      
    - name: Create build artifact
      id: set-output
      run: |
        mkdir -p build
        cp -r package*.json app.js build/
        # Create package-lock.json in build directory if it doesn't exist
        if [ ! -f build/package-lock.json ] && [ -f package-lock.json ]; then
          cp package-lock.json build/
        fi
        echo "artifact-name=node-app-$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.set-output.outputs.artifact-name }}
        path: build/
        retention-days: 5

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Show artifact info
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.artifact-name }}
        path: artifact
        
    - name: Show artifact contents
      run: |
        echo "Artifact contents:"
        ls -la artifact/
        echo -e "\nApplication can be started with:"
        echo "cd artifact && npm ci --production && node app.js"
        
    - name: Show deployment information
      run: |
        echo "Artifact was built from: $GITHUB_SHA"
        echo "Run number: $GITHUB_RUN_NUMBER"
        echo "Artifact name: ${{ needs.build.outputs.artifact-name }}"